= 東京工業女学院 短編集

== About
教育改革で女子校となった架空の大学・大学院『東京工業女学院』に関する短編集。

『東京工業女学院』の元ネタの詳細については link:http://togetter.com/li/925918[東京工業女学院 - Togetterまとめ] を参照のこと。
(ただし、必ずしもここで出た設定を採用するとは限らないことに留意せよ。)

物語中に現れる固有名詞(特に地名・組織・人物)は実在のものと酷似あるいは一致していることがあるが、実在のものとは一切関係がないということをここで述べておく。

== Directory structure / file formats
=== Directory structure
- `main/`
  * 本編のテキストファイルが配置される。
- `settings/`
  * 設定を記したファイルが配置される。
- `rationale/`
  * 物語の展開上で鉞が飛んできそうな箇所について、あらかじめ説明を行うファイルが配置される。
- `meta/`
  * このリポジトリや管理自体に関する情報や話題を記したファイルが配置される。

== File formats
原則として、リッチなテキストはasciidocフォーマットが望ましい。が、markdownでもよい。

本文だけは、例外としてplain text。
記法は、基本的に小説投稿サイト link:http://syosetu.com/[小説家になろう] に合わせるものとする。 +
特にルビの仕様については link:http://whiteleaf.hatenablog.com/entry/2013/03/27/%E5%B0%8F%E8%AA%AC%E5%AE%B6%E3%81%AB%E3%81%AA%E3%82%8D%E3%81%86%E3%81%AE%E3%83%AB%E3%83%93%E3%81%AE%E6%9B%B8%E3%81%8D%E6%96%B9%E3%83%BB%E4%BB%95%E6%A7%98%E3%81%AE%E8%A7%A3%E8%AA%AC[小説家になろうのルビの書き方・仕様の解説 - WHITELEAF：Kindle応援サイト] 等が参考になると思われる。

== Contributing
既存の設定を破壊しないような文章の投稿は歓迎される
(Pull Requestとか使えばいいのだろうか？私は使ったことがないので、よくわからない)。
特に、第1話の著者は機械系や制御系などには疎いため、様々な分野の文章を歓迎する。

プライバシー上の問題、誤字・脱字、設定や展開のおかしな点、文章のスタイルの問題、取り入れるべき設定、鉞などについては、Issuesに投げられよ。
ただし、誤解のありうる点や解説の必要な点、想定される鉞への対応などについては `rationale/` 内のファイルで行うことがあるため、そちらを確認してからにするべきである。

== その他
=== リポジトリとブランチ
このリポジトリやブランチの運用は、小説を構築・管理する方法の実験でもあり、予告なく変更される可能性がある。

=== 公開
このリポジトリに配置された本文ファイルは、 link:http://syosetu.com/[小説家になろう] に投稿することがある
(link:http://ncode.syosetu.com/n5062dd/[東京工業女学院 短編集])。
というか、原則する。
公開を拒否したい場合は、本文のヘッダかフッタにそう記されよ。
